-- AlterTable
ALTER TABLE "Settings" ADD COLUMN "cardButtonBgColor" TEXT NOT NULL DEFAULT '#FFFFFF';
ALTER TABLE "Settings" ADD COLUMN "cardButtonFontSize" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "Settings" ADD COLUMN "cardButtonText" TEXT NOT NULL DEFAULT 'PAY WITH CARD';
ALTER TABLE "Settings" ADD COLUMN "cardButtonTextColor" TEXT NOT NULL DEFAULT '#000000';
