query CartInput {
  cart {
    lines {
      id
      quantity
      giftAttribute: attribute(key: "_preventify_gift") {
        value
      }
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app:bundle-discount", key: "config") {
      jsonValue
    }
  }
}
